### ISSUE TITLE
Спроектировать базу данных для отдела кадров

### ISSUE THREAD

**Issue by rockstarhamster** [cronnoss/hr-staff-rest-api#1]
Построить ER модель БД:
1. Составить список сущностей
2. Составить список атрибутов для каждой и сущностей
3. Нормализовать схему
4. Спроектировать связи между таблицами
5. Защитить схему

**Comment by cronnoss** [comment]
В БД необходимо создать две таблицы: Отделы и Сотрудники.
БД должна заполняться тестовыми данными.
Для отделов хранить название отдела.
Для сотрудников хранить: отдел, ФИО сотрудника, дату его рождения и его зарплату.

**Comment by cronnoss** [comment]
Дополнение:
Для отделов хранить должность.
Для сотрудников хранить должность отдела.
[DBMS ER diagram (UML notation)2.pdf](https://github.com/cronnoss/hr-staff-rest-api/files/6051821/DBMS.ER.diagram.UML.notation.2.pdf)

**Comment by cronnoss** [comment]
Немного по другому. Так наверное лучше. 

> 1. Составить список сущностей

Лучше сделать в трех таблицах (сущностях): 
1. department, 
2. employee, 
3. position.

> 2. Составить список атрибутов для каждой и сущностей

Список атрибутов:
1. department
1.1.  depid 
1.2. department_name

2. employee
2.1.  empid 
2.2. full_name
2.3. date_of_birth
2.4. salary

3. position
3.1.  posid 
3.2. position_name

> 4. Спроектировать связи между таблицами
department => employee (один ко многим)
department => position (один ко многим)
employee <=> position (многие ко многим)
[1_DBMS ER diagram (UML notation)4.pdf](https://github.com/cronnoss/hr-staff-rest-api/files/6056842/1_DBMS.ER.diagram.UML.notation.4.pdf)

**Comment by rockstarhamster** [comment]
По поводу ER модели, очень сильно походит на циклическую зависимость. Всегда нужно стремиться чтобы какая-то сущность бы ла управляющей. В твоём случае я бы сделал так департамент -> должность -> работник. Если оставить твою модель, то могут возникнуть трудности, когда мы захотим, например, упразднить департамент и на него будут ссылаться какие-работники

**Comment by cronnoss** [comment]
Сделал так:

> 1. Составить список сущностей

1. department,
2. position,
3. employee.

> 2. Составить список атрибутов для каждой из сущностей

Список атрибутов:

1. department
1.1. depid
1.2. department_name

2. position
2.1. posid
2.2. depid 
2.3. position_name

3. employee
3.1. empid
3.2. full_name
3.3. date_of_birth
3.4. salary

> 4. Спроектировать связи между таблицами

department => position (один ко многим)
position <=> employee (многие ко многим)

[DBMS ER diagram (UML notation)5.pdf](https://github.com/cronnoss/hr-staff-rest-api/files/6057436/DBMS.ER.diagram.UML.notation.5.pdf)

**Comment by cronnoss** [comment]
Обновил ER модель. Поставил тип данных и констрейнты
[DBMS ER diagram (UML notation)6.pdf](https://github.com/cronnoss/hr-staff-rest-api/files/6057760/DBMS.ER.diagram.UML.notation.6.pdf)

**Comment by rockstarhamster** [comment]
Я бы еще добавил сразу туда NotNull & Unique constraints если есть

**Comment by cronnoss** [comment]
NotNull & Unique я в SQL скриптах уже прописал
https://github.com/cronnoss/hr-staff-rest-api/commit/37767edb8ab2ddd0897378395b0a0ba083f9fc22
