### ISSUE TITLE
Составить список use-cases для API

### ISSUE THREAD

**Issue by rockstarhamster** [cronnoss/hr-staff-rest-api#2]
Необходимо составить список сценариев по которым пользователь может взаимодействовать с API. Можно упороться и заюзать UML, а моно описать обычными словами

**Comment by cronnoss** [comment]
API должно позволять:

1. посмотреть список отделов и среднюю зарплату (рассчитывается автоматически) по этим отделам 
2. посмотреть список сотрудников в отделах с указанием зарплаты для каждого сотрудника
3. поиск сотрудников родившихся в определенную дату или в период между датами
4. изменять (добавлять/редактировать/удалять) вышеуказанные данные

**Comment by cronnoss** [comment]
Дополнение:
5. посмотреть список сотрудников в отделах с указанием зарплаты для каждого сотрудника, с указанием должности отдела.
